<a href="https://colab.research.google.com/github/cormac-black/chekhovs-biscuit/blob/main/IndexinWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
import numpy as np
import random


def make_array(h,w):
  h_enter = h
  w_enter = w
  g = np.zeros((h_enter,w_enter), dtype=int)

  hgt, wdt = g.shape

  for i in range(hgt):
      for j in range(wdt):
          a = random.randint(0,9)
          g[i,j] = a

  return g

a = make_array(5,5)
print(f'Matrix A:\n {a}\n\n')
b = make_array(5,5)
print(f'Matrix B: \n {b}\n')

try:
  y,x = np.where(a == 2)
  print(f'Matrix AB:\n {y,x}')
except:
  print("sorry no 2")

Matrix A:
 [[1 9 6 9 1]
 [6 7 8 3 3]
 [7 4 3 5 1]
 [6 5 0 8 6]
 [8 2 7 4 8]]


Matrix B: 
 [[0 5 7 6 0]
 [0 4 1 7 1]
 [0 6 9 2 0]
 [3 1 5 4 9]
 [8 9 8 3 5]]

Matrix AB:
 (array([4]), array([1]))
