<a href="https://colab.research.google.com/github/cormac-black/chekhovs-biscuit/blob/main/IndexinWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
import random


def make_array(h,w):
  h_enter = h
  w_enter = w
  g = np.zeros((h_enter,w_enter), dtype=int)

  hgt, wdt = g.shape

  for i in range(hgt):
      for j in range(wdt):
          a = random.randint(0,9)
          g[i,j] = a

  return g

a = make_array(5,5)
print(f'Matrix A:\n {a}\n\n')
b = make_array(5,5)
# print(f'Matrix B: \n {b}\n')

try:
  y,x = np.where(a == 2)
  print(f'Find the Twos:\n {y,x}')
except:
  print("sorry no 2")

Matrix A:
 [[7 7 9 6 7]
 [6 8 9 2 9]
 [0 9 2 3 9]
 [7 0 5 3 7]
 [4 2 2 2 1]]


Find the Twos:
 (array([1, 2, 4, 4, 4]), array([3, 2, 1, 2, 3]))
